[package]
name = "rcmlrs"
version = "0.1.0"
edition = "2021"
authors = ["Hadrian Lazic"]
license = "MIT"

[dependencies]

[workspace]
members = [
    "packages/cli",
    "packages/neuralnet-impls",
    "storage-op",
    "tensor-impls",
    "tensor-std-operations",
    "wasm-features",
]
