[package]
name = "rcmlrs"
version = "0.0.1"
edition = "2021"
authors = ["Hadrian Lazic"]
license = "MIT"

[dependencies]
rand = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3
